- hosts: terraform-ansible
  tasks:
  - name: instalando python3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: instalando dependencias com pip (Django e Djando Rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name: 
        - django
        - djangorestframework
    #iniciando cada função nova
  - name: verificando se o projeto existe
    #verificando se o arquivo está lá
    stat:
     path: /home/ubuntu/tcc/setup/settings.py
    #criando uma variavel
    register: projeto
  - name: iniciando o projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    when: not projeto.stat.exists
    #ignore_errors: yes
  - name: Alterando hosting do python settings
    lineinfile: 
      path: /home/ubuntu/tcc/setup/settings.py 
      regexp: 'ALLOWED_HOSTS' 
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes